version: '3.8'
services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.cpu
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./checkpoints:/app/checkpoints
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ../../frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
