# backend/docker/Dockerfile.cpu
FROM python:3.10-slim
WORKDIR /app
COPY ../requirements.txt /app/requirements.txt
RUN apt-get update && apt-get install -y ffmpeg libsm6 libxrender1 libxext6 && rm -rf /var/lib/apt/lists/*
RUN pip install --upgrade pip
RUN pip install -r /app/requirements.txt
COPY .. /app
ENV MODEL_PATH=/app/checkpoints/best_model.pth
EXPOSE 8000
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
